#!/usr/bin/env bash

# Setup fzf
# ---------
if [[ ! "$PATH" == */opt/homebrew/opt/fzf/bin* ]]; then
    PATH="${PATH:+${PATH}:}/opt/homebrew/opt/fzf/bin"
fi

# Auto-completion
# ---------------
if [[ $- == *i* ]]; then
    source "/opt/homebrew/opt/fzf/shell/completion.zsh" 2> /dev/null
fi

# Key bindings
# ------------
source "/opt/homebrew/opt/fzf/shell/key-bindings.zsh"
