git:
  overrideGpg: true

os:
  editPreset: nvim

gui:
  useHunkModeInStagingView: false
  border: 'single'
  branchColors:
    'master': red

  nerdFontsVersion: '3'

  filterMode: fuzzy

  theme:
    selectedLineBgColor:
      - reverse
