git:
  overrideGpg: true
  autoForwardBranches: none

keybinding:
  universal:
    scrollUpMain-alt1: <c-k>
    scrollDownMain-alt1: <c-j>
  commits:
    moveUpCommit: K
    moveDownCommit: J

os:
  editPreset: nvim

gui:
  useHunkModeInStagingView: false
  border: 'single'
  branchColors:
    'master': red

  nerdFontsVersion: '3'

  filterMode: fuzzy

  theme:
    showDivergenceFromBaseBranch: arrowAndNumber
    selectedLineBgColor:
      - reverse
