#!/usr/bin/env bash

# Header logging
function e_header() {
  printf "\n$(tput setaf 7)%s$(tput sgr0)\n" "$@"
}

# Success logging
function e_success() {
  printf "$(tput setaf 65) $(tput sgr0) %s\n" "$@"
}

# Error logging
function e_error() {
  printf "$(tput setaf 1) $(tput sgr0) %s\n" "$@"
}

# Warning logging
function e_warning() {
  printf "$(tput setaf 137) $(tput sgr0) %s\n" "$@"
}

# Ask for confirmation before proceeding
function seek_confirmation() {
  printf "\n"
  e_warning "$@"
  read -p "Continue? (y/n) " -n 1
  printf "\n"
}

# Test whether the result of an 'ask' is a confirmation
function is_confirmed() {
  if [[ "$REPLY" =~ ^[Yy]$ ]]; then
    return 0
  fi
  return 1
}

# Test whether we're in a git repo
function is_git_repo() {
  $(git rev-parse --is-inside-work-tree &> /dev/null)
}

# Test whether a command exists
# $1 - cmd to test
function type_exists() {
  if [ $(type -P $1) ]; then
    return 0
  fi
  return 1
}
