[mgr]
find_keyword = {bg = "black", fg = "red", reversed = true}
marker_copied   = {fg = "green", bg = "green"}
marker_cut      = {fg = "red", bg = "red"}
marker_marked   = {fg = "magenta", bg = "magenta"}
marker_selected = {fg = "cyan", bg = "cyan"}
cwd = {fg = "yellow"}
hovered = {reversed = true}
preview_hovered = {reversed = true}
tab_active   = {reversed = true}
tab_inactive = {}
tab_width    = 1
count_copied   = {fg = "reset", bg = "green"}
count_cut      = {fg = "reset", bg = "red"}
count_selected = {fg = "reset", bg = "yellow"}
border_style = {fg = "white"}

[mode]
normal_main = {fg = "red", bg = "reset"}
select_main = {fg = "magenta", bg = "reset"}
unset_main  = {fg = "yellow", bg = "reset"}


[status]
sep_left = {open = "", close = ""}
sep_right = {open = "", close = ""}
progress_label  = {fg = "blue", bg = "black", bold = true}
progress_normal = {fg = "darkgrey", bg = "black"}
progress_error  = {fg = "darkgrey", bg = "black"}
perm_type = {fg = "green"}
perm_read = {fg = "yellow"}
perm_write = {fg = "red"}
perm_exec = {fg = "cyan"}
perm_sep = {fg = "magenta"}

[select]
border = {fg = "blue"}
active = {fg = "magenta"}
inactive = {}
