# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Get updates automatically
zstyle ':omz:update' mode auto
zstyle ':omz:update' frequency 14
zstyle ':omz:update' verbose default # default update prompt

# Path to your oh-my-zsh installation.
export ZSH="$HOME/dotfiles/zsh/oh-my-zsh"

ZSH_THEME="gonzalostoll"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM="$HOME/dotfiles/zsh/oh-my-zsh-custom/"

plugins=(git zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

alias ..="cd .. && cd .."
# npm aliases
[ -f ~/dotfiles/zsh/aliases/npm.zsh ] && source ~/dotfiles/zsh/aliases/npm.zsh
# pnpm aliases
[ -f ~/dotfiles/zsh/aliases/pnpm.zsh ] && source ~/dotfiles/zsh/aliases/pnpm.zsh
# Lazygit
[ -f ~/dotfiles/zsh/aliases/git.zsh ] && source ~/dotfiles/zsh/aliases/git.zsh
# Neovim
[ -f ~/dotfiles/zsh/aliases/neovim.zsh ] && source ~/dotfiles/zsh/aliases/neovim.zsh

# Syntax highlighting
source ${HOMEBREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# z for navigation jumping
. ~/dotfiles/zsh/z.sh

# Shell integration
source ~/dotfiles/zsh/iterm2_shell_integration.zsh

# fzf
[ -f ~/dotfiles/zsh/fzf.zsh ] && source ~/dotfiles/zsh/fzf.zsh
[ -f ~/dotfiles/zsh/aliases/fzf.zsh ] && source ~/dotfiles/zsh/aliases/fzf.zsh

# bun completions
[ -s "/Users/gonzalostoll/.bun/_bun" ] && source "/Users/gonzalostoll/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
