# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

ZSHRC_PATH=$(readlink .zshrc) # get the path of the .zshrc symlink
ZSH_PATH=$(dirname $ZSHRC_PATH) # get the path of the zsh folder

# Get updates automatically
zstyle ':omz:update' mode auto
zstyle ':omz:update' frequency 14
zstyle ':omz:update' verbose default # default update prompt

# Path to your oh-my-zsh installation.
export ZSH="$ZSH_PATH/oh-my-zsh"

ZSH_THEME="gonzalostoll"

# Custom folder for $ZSH/custom?
ZSH_CUSTOM="$ZSH_PATH/oh-my-zsh-custom/"

plugins=(git zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

export TERM=xterm-256color
export TERMINFO='/usr/share/terminfo/'

# Bun
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Syntax highlighting
source ${HOMEBREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# z for navigation jumping
source $ZSH_PATH/z.sh

# Shell integration
source $ZSH_PATH/iterm2_shell_integration.zsh

# fzf
source $ZSH_PATH/fzf.zsh

#################################### ALIASES ####################################
# navigation
source $ZSH_PATH/aliases/navigation.zsh
# runtime
source $ZSH_PATH/aliases/runtime.zsh
# Lazygit
source $ZSH_PATH/aliases/git.zsh
# Neovim
source $ZSH_PATH/aliases/neovim.zsh
source $ZSH_PATH/aliases/fzf.zsh
